version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: swapanza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bakugan2005
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: swapanzaBackend/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=swapanzaBackend.settings
      - DJANGO_SECRET_KEY=django-insecure-sh%pzqu4(zfuax&i(uglk&nhd5d#&4msx!+&l=_s$!%73*_s(l
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:80,http://frontend:80
      - CORS_ALLOW_CREDENTIALS=True
      - DATABASE_URL=postgresql://postgres:bakugan2005@db:5432/swapanza
      - REDIS_URL=redis://redis:6379/0
      - CLOUDINARY_CLOUD_NAME=dfxbvixpv
      - CLOUDINARY_API_KEY=288166313734759
      - CLOUDINARY_API_SECRET=rj5ziHFTOQTuWXrl_VZU98xi-Dc
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  # Celery Worker (optional - for background tasks)
  celery:
    build:
      context: .
      dockerfile: swapanzaBackend/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=swapanzaBackend.settings
      - DJANGO_SECRET_KEY=django-insecure-sh%pzqu4(zfuax&i(uglk&nhd5d#&4msx!+&l=_s$!%73*_s(l
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgresql://postgres:bakugan2005@db:5432/swapanza
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A swapanzaBackend worker --loglevel=info

volumes:
  postgres_data:
  redis_data: 