# Generated by Django 5.1.5 on 2025-02-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_user_profile_image_public_id_user_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_switched',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='original_user_1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='original_user_2',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='switch_accepted_by_user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='switch_accepted_by_user2',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='switch_ends_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='switch_requested_by',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='switch_started_at',
        ),
    ]
