# Generated by Django 5.1.6 on 2025-03-24 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_user_bio_alter_user_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='swapanza_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='swapanza_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='chat',
            name='swapanza_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='swapanza_message_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chat',
            name='swapanza_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='swapanza_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='during_swapanza',
            field=models.BooleanField(default=False),
        ),
    ]
