# Generated by Django 5.1.6 on 2025-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chat_swapanza_active_chat_swapanza_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='swapanza_confirmed_users',
            field=models.JSONField(default=list),
        ),
    ]
