# Generated by Django 5.1.6 on 2025-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_swapanzasession'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapanzasession',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
