# Generated by Django 5.1.5 on 2025-02-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='switch_accepted_by',
        ),
        migrations.AddField(
            model_name='chat',
            name='switch_accepted_by_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='switch_accepted_by_user2',
            field=models.BooleanField(default=False),
        ),
    ]
