# Generated by Django 5.1.6 on 2025-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chat_swapanza_confirmed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='apparent_sender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
