# Generated by Django 5.1.6 on 2025-04-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_swapanzasession_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapanzasession',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swapanza_sessions', to='chat.chat'),
        ),
    ]
