# Generated by Django 5.1.6 on 2025-04-03 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_remove_message_seen_remove_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='swapanza_confirmed_users',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='swapanza_duration',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='swapanza_message_count',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='swapanza_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapanza_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='apparent_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apparent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
