# Generated by Django 5.1.6 on 2025-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_chat_swapanza_confirmed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='swapanza_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
