# Generated by Django 5.1.6 on 2025-04-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_chat_swapanza_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='apparent_sender_profile_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='apparent_sender_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
